name: winterflowspace-api

namespace: kavanest
env:
  APP_VERSION: 834bb4fb8bdaf29b8e9e497b9f4c2cdb8a8115e2

deployment:
  - name: winterflowspace-api
    image: invisibug/winterflowspace-api
    ports:
      - port: 3000

ingress:
  - name: api.winterflowspace.com
    selector: winterflowspace-api
    path: /
    port: 3000
    host: api.winterflowspace.com

service:
  loadBalancer:
    - name: winterflowspace-api
      selector: winterflowspace-api
      port: 80
      containerPort: 3000
