name: winterflowspace-api

namespace: kavanest
env:
  APP_VERSION: c0e796c359898416a865e6eb070f97dcbbd0a504

deployment:
  - name: winterflowspace-api
    image: invisibug/winterflowspace-api
    ports:
      - port: 3000

ingress:
  - name: api.kavanet.io
    selector: winterflowspace-api
    path: /
    port: 3000
    host: api.kavanet.io

service:
  loadBalancer:
    - name: winterflowspace-api
      selector: winterflowspace-api
      port: 80
      containerPort: 3000
