name: winterflowspace-api

namespace: kavanest
env:
  APP_VERSION: d15da55fe6aed4685ce89dff6bdf3fa7d03339cf

deployment:
  - name: winterflowspace-api
    image: invisibug/winterflowspace-api
    ports:
      - port: 3000

ingress:
  - name: api.kavanet.io
    selector: winterflowspace-api
    path: /
    port: 3000
    host: api.kavanet.io

service:
  loadBalancer:
    - name: winterflowspace-api
      selector: winterflowspace-api
      port: 80
      containerPort: 3000
